import React, { useEffect, useState } from "react";
import { Alert, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import * as LocalAuthentication from "expo-local-authentication";
import { unlockWithPin, vaultFallbackMode, vaultMode, SecretMode, VaultMode } from "../services/offlineVault";

export default function VaultLockScreen({ onUnlock }: { onUnlock: () => void }) {
  const [secret, setSecret] = useState(""); const [mode, setMode] = useState<VaultMode>("pin"); const [useBackup, setUseBackup] = useState(false); const [backupMode, setBackupMode] = useState<SecretMode>("pin");
  useEffect(() => { vaultMode().then(async (savedMode) => { setMode(savedMode); const backup = await vaultFallbackMode(); if (backup) setBackupMode(backup); }); }, []);
  const bySecret = async () => { if (await unlockWithPin(secret)) onUnlock(); else Alert.alert("Nieprawidłowe dane", "Sprawdź PIN lub hasło i spróbuj ponownie."); };
  const byBiometric = async () => { const available = await LocalAuthentication.hasHardwareAsync() && await LocalAuthentication.isEnrolledAsync(); if (!available) return Alert.alert("Biometria niedostępna", "Ustaw odcisk palca lub twarz albo użyj PIN-u/hasła awaryjnego."); const result = await LocalAuthentication.authenticateAsync({ promptMessage: "Otwórz E‑Teczkę", promptDescription: "Potwierdź swoją tożsamość", biometricsSecurityLevel: "strong", disableDeviceFallback: true }); if (result.success) onUnlock(); };
  const biometricPrimary = mode === "biometric" && !useBackup; const secretMode: SecretMode = mode === "biometric" ? backupMode : mode;
  return <View style={styles.container}><Ionicons name="shield-checkmark" size={70} color="#60a5fa" /><Text style={styles.title}>E‑Teczka jest zablokowana</Text><Text style={styles.text}>Otwórz aplikację wybraną metodą. Kopie offline pozostają zaszyfrowane na telefonie.</Text>{biometricPrimary ? <><TouchableOpacity style={styles.bio} onPress={byBiometric}><Ionicons name="finger-print" size={24} color="white" /><Text style={styles.buttonText}>Otwórz biometrią telefonu</Text></TouchableOpacity><TouchableOpacity style={styles.alternative} onPress={() => setUseBackup(true)}><Text style={styles.alternativeText}>Użyj {backupMode === "pin" ? "PIN-u" : "hasła"} zamiast biometrii</Text></TouchableOpacity></> : <><TextInput value={secret} onChangeText={setSecret} keyboardType={secretMode === "pin" ? "number-pad" : "default"} secureTextEntry placeholder={secretMode === "pin" ? "Wpisz PIN" : "Wpisz hasło"} placeholderTextColor="#64748b" style={styles.input} onSubmitEditing={bySecret} /><TouchableOpacity style={styles.pin} onPress={bySecret}><Text style={styles.buttonText}>{secretMode === "pin" ? "Otwórz PIN-em" : "Otwórz hasłem"}</Text></TouchableOpacity>{mode === "biometric" && <TouchableOpacity style={styles.alternative} onPress={() => { setUseBackup(false); setSecret(""); }}><Text style={styles.alternativeText}>Wróć do biometrii</Text></TouchableOpacity>}</>}<Text style={styles.hint}>{mode === "biometric" ? `Awaryjnie możesz użyć ${backupMode === "pin" ? "PIN-u" : "hasła"}.` : "Metodę otwierania można zmienić w Ustawieniach po potwierdzeniu obecnego dostępu."}</Text></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: "#0f172a", alignItems: "center", justifyContent: "center", padding: 28, gap: 14 }, title: { color: "white", fontSize: 27, fontWeight: "bold" }, text: { color: "#cbd5e1", textAlign: "center", fontSize: 14, marginBottom: 14 }, input: { width: "100%", color: "white", borderColor: "#475569", borderWidth: 1, backgroundColor: "#1e293b", borderRadius: 10, padding: 14, fontSize: 18, textAlign: "center" }, pin: { width: "100%", backgroundColor: "#2563eb", padding: 14, borderRadius: 10, alignItems: "center" }, bio: { width: "100%", backgroundColor: "#16a34a", padding: 14, borderRadius: 10, alignItems: "center", flexDirection: "row", justifyContent: "center", gap: 8 }, buttonText: { color: "white", fontWeight: "800", fontSize: 15 }, alternative: { paddingVertical: 8 }, alternativeText: { color: "#93c5fd", fontWeight: "700", fontSize: 13 }, hint: { color: "#94a3b8", textAlign: "center", fontSize: 12, marginTop: 12 } });
