import { useState } from 'react';

type Props = { apiUrl: string; onClose: () => void; onDone: () => void };

export default function BackupModal({ apiUrl, onClose, onDone }: Props) {
  const [destination, setDestination] = useState<'computer' | 'qnap'>('computer');
  const [qnapPath, setQnapPath] = useState('');
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const authHeaders = (): Record<string, string> => { const token = localStorage.getItem('eteczka_auth_token'); return token ? { Authorization: `Bearer ${token}` } : {}; };
  const backup = async () => {
    setBusy(true); setMessage('Tworzenie kopii…');
    try { const response = await fetch(`${apiUrl}/api/backup/export`, { headers: authHeaders() }); if (!response.ok) throw new Error('Nie udało się utworzyć kopii.'); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `eteczka-backup-${new Date().toISOString().slice(0, 10)}.zip`; link.click(); URL.revokeObjectURL(url); setMessage(destination === 'qnap' && qnapPath ? `Pobierz plik i skopiuj go na QNAP: ${qnapPath}` : 'Kopia została pobrana. Przechowuj ją w wybranej chmurze lub na QNAP.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Błąd tworzenia kopii.'); } finally { setBusy(false); }
  };
  const restore = async (file: File) => { setBusy(true); setMessage('Przywracanie kopii…'); try { const body = new FormData(); body.append('backup', file); const response = await fetch(`${apiUrl}/api/backup/restore`, { method: 'POST', headers: authHeaders(), body }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || 'Nie udało się przywrócić kopii.'); setMessage(`Przywrócono ${payload.restoredDocuments || 0} dokumentów.`); onDone(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Błąd przywracania kopii.'); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-[120] flex items-center justify-center overflow-y-auto bg-black/80 p-4"><section className="my-6 w-full max-w-lg rounded-2xl border border-slate-600 bg-[#0f172a] p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold text-white">☁️ Kopia zapasowa</h2><p className="mt-1 text-sm text-slate-400">Eksportuj lub przywróć dokumenty i kartoteki.</p></div><button onClick={onClose} className="text-xl text-slate-400">×</button></div><label className="mt-5 block text-sm font-semibold text-slate-300">Miejsce przechowywania</label><select value={destination} onChange={event => setDestination(event.target.value as 'computer' | 'qnap')} className="mt-2 w-full rounded-lg border border-slate-600 bg-[#111827] p-3 text-white"><option value="computer">Komputer / dowolna chmura</option><option value="qnap">QNAP / NAS</option></select>{destination === 'qnap' && <input value={qnapPath} onChange={event => setQnapPath(event.target.value)} placeholder="Ścieżka udziału QNAP, np. \\NAS\Backup" className="mt-3 w-full rounded-lg border border-slate-600 bg-[#111827] p-3 text-white" />}<button disabled={busy} onClick={() => void backup()} className="mt-5 w-full rounded-lg bg-blue-600 py-3 font-bold text-white disabled:opacity-50">{busy ? 'Przetwarzanie…' : 'Utwórz i pobierz kopię ZIP'}</button><label className="mt-4 block cursor-pointer rounded-lg border border-dashed border-slate-500 p-4 text-center text-sm text-slate-300 hover:border-blue-400"><span>Wybierz kopię do przywrócenia</span><input disabled={busy} type="file" accept=".zip,application/zip" className="hidden" onChange={event => { const file = event.target.files?.[0]; if (file) void restore(file); }} /></label>{message && <p className="mt-4 rounded-lg bg-slate-800 p-3 text-sm text-slate-300">{message}</p>}<p className="mt-4 text-xs leading-5 text-slate-500">Kopia zawiera metadane i pliki dokumentów. Plik ZIP przechowuj w prywatnej, szyfrowanej lokalizacji.</p></section></div>;
}
