import { useEffect, useState } from 'react';
import { getElectronIpc, isAccessResult, isAccessStatus, type AccessMode } from './services/electron';

export default function DesktopAccessSettings({ onClose }: { onClose: () => void }) {
  const [currentMode, setCurrentMode] = useState<AccessMode>('pin'); const [nextMode, setNextMode] = useState<AccessMode>('pin'); const [currentSecret, setCurrentSecret] = useState(''); const [nextSecret, setNextSecret] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { void (async () => { try { const response = await getElectronIpc()?.invoke('eteczka-access-status'); if (isAccessStatus(response) && response.mode) { setCurrentMode(response.mode); setNextMode(response.mode); } } catch { setMessage('Nie można odczytać ustawień zabezpieczeń.'); } })(); }, []);
  const save = async () => { const api = getElectronIpc(); if (!api) return; setMessage(''); try { const verification = await api.invoke('eteczka-access-verify', currentSecret); if (!isAccessResult(verification) || !verification.ok) { setMessage('Nieprawidłowy obecny PIN lub hasło.'); return; } const updated = await api.invoke('eteczka-access-configure', { mode: nextMode, secret: nextSecret }); if (!isAccessResult(updated) || !updated.ok) { setMessage(isAccessResult(updated) ? updated.error ?? 'Nie udało się zapisać ustawień.' : 'Nieprawidłowa odpowiedź blokady.'); return; } onClose(); } catch { setMessage('Nie można zapisać ustawień zabezpieczeń.'); } };
  return <div className="fixed inset-0 z-[100] bg-slate-950/80 flex items-center justify-center p-5"><section className="w-full max-w-md bg-[#1e293b] border border-slate-600 rounded-xl p-6 shadow-2xl"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-bold text-white">🔐 Zabezpieczenia</h2><p className="text-sm text-slate-400 mt-1">Zmiana wymaga potwierdzenia obecnego dostępu.</p></div><button onClick={onClose} className="text-slate-400 hover:text-white text-xl">×</button></div><label className="block text-sm font-semibold text-slate-300 mt-6">Obecne {currentMode === 'pin' ? 'PIN' : 'hasło'}</label><input autoFocus type="password" inputMode={currentMode === 'pin' ? 'numeric' : 'text'} value={currentSecret} onChange={event => setCurrentSecret(event.target.value)} className="mt-2 w-full rounded-lg border border-slate-600 bg-[#0f172a] px-3 py-3 text-white outline-none focus:border-blue-500" /><p className="text-sm font-semibold text-slate-300 mt-5">Nowa metoda otwierania</p><div className="flex gap-2 mt-2"><button onClick={() => setNextMode('pin')} className={`flex-1 py-2.5 rounded-lg font-bold ${nextMode === 'pin' ? 'bg-blue-600 text-white' : 'bg-slate-700 text-slate-300'}`}>PIN</button><button onClick={() => setNextMode('password')} className={`flex-1 py-2.5 rounded-lg font-bold ${nextMode === 'password' ? 'bg-blue-600 text-white' : 'bg-slate-700 text-slate-300'}`}>Hasło</button></div><input type="password" inputMode={nextMode === 'pin' ? 'numeric' : 'text'} value={nextSecret} onChange={event => setNextSecret(event.target.value)} placeholder={nextMode === 'pin' ? 'Nowy PIN: min. 6 cyfr' : 'Nowe hasło: min. 8 znaków'} className="mt-3 w-full rounded-lg border border-slate-600 bg-[#0f172a] px-3 py-3 text-white outline-none focus:border-blue-500" />{message && <p className="text-sm text-red-400 mt-3">{message}</p>}<button onClick={save} className="w-full bg-blue-600 hover:bg-blue-500 rounded-lg py-3 font-bold text-white mt-5">Potwierdź i zapisz</button></section></div>;
}
